### ISSUE TITLE
Displays invalid JSON due to the small issue

### ISSUE THREAD

**Issue by LINKeRxUA** [ArjunVarshney/jsontohtml-render#1]
When JSON is rendered, each line ends with a comma character. According to the JSON linter that is not valid. Let me ask you to add a check to skip adding the comma for the last element in a list. 

Thanks in advance

Valid JSON example:
```JSON
{

    "some_key": "value",
    "list": [
        "a",
        "b",
        "c"
    ]
}
```
Invalid render output:
![Screenshot 2023-10-27 at 12 48 02](https://github.com/ArjunVarshney/jsontohtml-render/assets/21177131/cbb08f07-bb91-4d48-829f-f11721c1e766)

**Comment by ArjunVarshney** [comment]
I have fixed it. You can run `npm update jsontohtml-render` to update the package or change the asset file to `https://cdn.jsdelivr.net/gh/ArjunVarshney/jsontohtml-render@main/dist/index.js`
